grafana:
  adminPassword: "admin"
  service:
    type: NodePort
    nodePort: 30300
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: "500m"
      memory: 512Mi
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'llama'
        orgId: 1
        folder: 'LLaMA'
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/llama
  dashboards:
    llama:
      llama-dashboard:
        file: dashboards/llama-dashboard.json
  additionalDataSources:
    - name: prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      isDefault: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
  service:
    type: NodePort
    nodePort: 30900
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: "500m"
      memory: 512Mi

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  resources:
    limits:
      cpu: "200m"
      memory: 256Mi
    requests:
      cpu: "100m"
      memory: 128Mi
  admissionWebhooks:
    enabled: false
