{{- if .Values.ray.enabled }}
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: {{ .Values.ray.cluster.name | default (printf "%s-ray-cluster" (include "llama-server.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llama-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: ray-cluster
spec:
  rayVersion: {{ .Values.ray.version | quote }}
  headGroupSpec:
    rayStartParams:
      dashboard-host: '0.0.0.0'
      dashboard-port: '8265'
      port: '6379'
      block: 'true'
    template:
      spec:
        containers:
          - name: ray-head
            image: {{ .Values.ray.image.repository }}:{{ .Values.ray.image.tag }}
            imagePullPolicy: {{ .Values.ray.image.pullPolicy }}
            ports:
              - containerPort: 6379
                name: gcs
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
              - containerPort: 8000
                name: serve
            resources:
              {{- toYaml .Values.ray.headResources | nindent 14 }}
            volumeMounts:
              - name: models
                mountPath: /models
        volumes:
          - name: models
            persistentVolumeClaim:
              claimName: {{ .Values.persistence.name | default (printf "%s-models" (include "llama-server.fullname" .)) }}
  workerGroupSpecs:
    - groupName: small-workers
      replicas: {{ .Values.ray.workers.replicas }}
      minReplicas: {{ .Values.ray.workers.minReplicas }}
      maxReplicas: {{ .Values.ray.workers.maxReplicas }}
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-worker
              image: {{ .Values.ray.image.repository }}:{{ .Values.ray.image.tag }}
              imagePullPolicy: {{ .Values.ray.image.pullPolicy }}
              resources:
                {{- toYaml .Values.ray.workerResources | nindent 16 }}
              volumeMounts:
                - name: models
                  mountPath: /models
          volumes:
            - name: models
              persistentVolumeClaim:
                claimName: {{ .Values.persistence.name | default (printf "%s-models" (include "llama-server.fullname" .)) }}
{{- end }}